name: "Run Command and Save Report"

description: "Checkout Code, Setup Python, Install Dependencies and run Command"

inputs:
  deps-directory:
    description: Where to search for requirements files.
    required: false
    default: "."
    type: string

  application-deps:
    description: Whether to install application dependencies.
    required: false
    default: false
    type: boolean

  quality-deps:
    description: Whether to install quality assurance dependencies.
    required: false
    default: false
    type: boolean

  security-deps:
    description: Whether to install security dependencies.
    required: false
    default: false
    type: boolean

  test-deps:
    description: Whether to install test dependencies.
    required: false
    default: false
    type: boolean

  source-directory:
    description: Where to run the command.
    required: false
    default: "."
    type: string

  command:
    description: What command to run.
    required: true
    type: string

  report:
    description: Whether to save a report.
    required: false
    default: false
    type: boolean

  report-key:
    description: Report Artifact Key.
    required: false
    type: string

  report-file:
    description: Report File.
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Load Cache & Dependencies.
      uses: cristovamsilva/python-dependencies-action@master
      with:
        deps-directory: ${{ inputs.deps-directory }}
        application: ${{ inputs.application-deps }}
        quality: ${{ inputs.quality-deps }}
        security: ${{ inputs.security-deps }}
        test: ${{ inputs.test-deps }}

    - name: Run Command.
      run: ${{ inputs.command }}
      shell: bash
      working-directory: ${{ inputs.source-directory }}

    - name: Upload Results.
      if: inputs.report && always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.report-key }}
        path: ${{ inputs.report-file }}
